EmailManager/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmailManager.Models {
    public class AppDbContext : DbContext{
        public AppDbContext(DbContextOptions<AppDbContext> options) :base(options) {

        }

        public DbSet<Customer> Customers { get; set; }
    }
}

EmailManager/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EmailManager.Models {
    [Table("email_ref")]
    public class Customer {
        [Column("CUSTOMER_NO")]
        [Key]
        [Display(Name ="Customer Number")]
        [Required(ErrorMessage="Customer Number is required")]
        public string CustomerNo { get; set; }
        
        [Column("COMPANY_NAME")]
        [Display(Name ="Company Name")]
        [Required(ErrorMessage ="Company Name is required")]
        public string CompanyName { get; set; }

        [Column("Z_REPORT_DIST")]
        [Display(Name ="Distribution List")]
        [Required(ErrorMessage ="Email distribution is required")]
        public string Emails { get; set; }

    }
}

EmailManager/Controllers/CustomerManagerController.cs
using EmailManager.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmailManager.Controllers {
    public class CustomerManagerController : Controller {
        private AppDbContext db = null;
        public CustomerManagerController(AppDbContext db) {
            this.db = db;
        }

        public IActionResult List() {
            List<Customer> model = (from c in db.Customers
                                    orderby c.CustomerNo
                                    select c).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult Insert() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Customer model) {
            if (ModelState.IsValid) {
                db.Customers.Add(model);
                db.SaveChanges();
                ViewBag.Message = "Customer added successfully";
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Update(string id) {
            var model = db.Customers.Find(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Customer model) {
            if (ModelState.IsValid) {
                db.Customers.Update(model);
                db.SaveChanges();
                ViewBag.Message = "Customer updated successfully";
            }

            return View(model);
        }

        [HttpGet]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(string id) {
            var model = db.Customers.Find(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string id) {
            var model = db.Customers.Find(id);
            db.Customers.Remove(model);
            db.SaveChanges();
            TempData["Message"] = "Employee Deleted Successfully";
            return RedirectToAction("List");
        }
    }
}

EmailManager/Views/CustomerManager/Delete.cshtml
@model Customer
<h2>Delete a Customer</h2>
<h3 class="message">
    Warning: You are about to delete a customer record!
</h3>

<form asp-controller="CustomerManager" asp-action="Delete" method="post">
    <input type="hidden" asp-for="CustomerNo" />
    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="CustomerNo"></label>
            </td>
            <td>@Model.CustomerNo</td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="CompanyName"></label>
            </td>
            <td>@Model.CompanyName</td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Emails"></label>
            </td>
            <td>@Model.Emails</td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Delete</button>
            </td>
        </tr>
    </table>
</form>

<br/><br/>
<a asp-controller="CustomerManager" asp-action="List">Back to Customer Listing</a>

EmailManager/Views/CustomerManager/Insert.cshtml
@model Customer

<h2>Insert New Customer</h2>
<h3 class="message">@ViewBag.Message</h3>

<form asp-controller="CustomerManager" asp-action="Insert" method="post">
    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="CustomerNo"></label>
            </td>
            <td>
                <input type="text" asp-for="CustomerNo" />
                <span asp-validation-for="CustomerNo" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="CompanyName"></label>
            </td>
            <td>
                <input type="text" asp-for="CompanyName" />
                <span asp-validation-for="CompanyName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Emails"></label>
            </td>
            <td>
                <textarea asp-for="Emails" rows="5" cols="40"></textarea>
                <span asp-validation-for="Emails" class="message"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
</form>
<br/><br/>
<a asp-controller="CustomerManager" asp-action="List">Back to Customer Listing</a>

EmailManager/Views/CustomerManager/List.cshtml
@model List<Customer>
<h2>List of Customers</h2>
<h2 class="message">@TempData["Message"]</h2>

<a asp-controller="CustomerManager" asp-action="Insert" class="linkbutton">Insert</a>

<br/><br/>
<table border="1" style="width: 100%">
    <colgroup>
        <col span="2" style="width: 15%" />
        <col span="1" style="width: 15%" />
        <col span="1" style="width: 15%" />
        <col span="1" style="width: 25%" />
    </colgroup>
    <tbody>
    <tr>
        <th colspan="2">Actions</th>
        <th>Customer No</th>
        <th>Company Name</th>
        <th>Distribution List</th>
    </tr>
    @foreach(var item in Model) {
        <tr>
            <td>
                <a asp-controller="CustomerManager" asp-action="Update" asp-route-id="@item.CustomerNo"
                   class="linkbutton">Update</a>
            </td>
            <td>
                <a asp-controller="CustomerManager" asp-action="Delete" asp-route-id="@item.CustomerNo"
                   class="linkbutton">Delete</a>
            </td>
            <td>@item.CustomerNo</td>
            <td>@item.CompanyName</td>
            <td>@item.Emails</td>
        </tr>
    }
        </tbody>
</table>

EmailManager/Views/CustomerManager/Update.cshtml
@model Customer

<h2>Update a Customer</h2>
<h3 class="message">@ViewBag.Message</h3>

<form asp-controller="CustomerManager" asp-action="Update" method="post">
    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="CustomerNo"></label>
            </td>
            <td>
                <input type="hidden" asp-for="CustomerNo" />
                <span>@Model.CustomerNo</span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="CompanyName"></label>
            </td>
            <td>
                <input type="text" asp-for="CompanyName" />
                <span asp-validation-for="CompanyName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Emails"></label>
            </td>
            <td>
                <textarea asp-for="Emails" rows="5" cols="40"></textarea>
                <span asp-validation-for="Emails" class="message"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
</form>
<br />
<br />
<a asp-controller="CustomerManager" asp-action="List">Back to Customer Listing</a>

EmailManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Customer Manager</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h1>Customer Manager</h1>
    <div>@RenderBody()</div>
    <br/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>